version: '3'

networks:
  app-tier:
    driver: bridge

services:
  githubapi:
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
    - app-tier
    links:
      - redis

  redis:
    #image: 'bitnami/redis:latest'
    build: redis/.
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /redis/data:/bitnami/redis/data
    networks:
    - app-tier
    expose:
      - 6379
    ports:
    - '6379:6379'